class CatalogExporter:

    def export(self, audio_assets, analytics, output_file):

        if not audio_assets:
            print("Nenhum asset para exportar.")
            return

        data = [asset.to_dict() for asset in audio_assets]
        headers = list(data[0].keys())

        rows_html = ""
        for item in data:
            cells = "".join(f"<td>{item.get(h, '')}</td>" for h in headers)
            rows_html += f"<tr>{cells}</tr>\n"

        headers_html = "".join(f"<th>{h.replace('_', ' ').title()}</th>" for h in headers)

        analytics_html = ""
        if analytics:
            analytics_html = f"""
            <div class="analytics">
                <h2>Batch Analytics</h2>
                <div class="analytics-grid">
                    <div class="card"><span>Total de Arquivos</span><strong>{analytics['total_files']}</strong></div>
                    <div class="card"><span>BPM Médio</span><strong>{analytics['bpm_average']}</strong></div>
                    <div class="card"><span>BPM Mais Alto</span><strong>{analytics['bpm_highest']}</strong></div>
                    <div class="card"><span>BPM Mais Baixo</span><strong>{analytics['bpm_lowest']}</strong></div>
                    <div class="card"><span>Duração Total</span><strong>{analytics['total_duration_minutes']} min</strong></div>
                    <div class="card"><span>Tonalidade Comum</span><strong>{analytics['most_common_key']}</strong></div>
                    <div class="card"><span>Gêneros</span><strong>{', '.join(analytics['genres_found'])}</strong></div>
                </div>
            </div>
            """

        html = f"""<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Audio Asset Catalog</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: 'Segoe UI', sans-serif; background: #0f0f0f; color: #e0e0e0; padding: 40px; }}
        h1 {{ font-size: 2rem; color: #ffffff; margin-bottom: 8px; }}
        .subtitle {{ color: #888; margin-bottom: 40px; font-size: 0.95rem; }}
        .analytics {{ margin-bottom: 40px; }}
        .analytics h2 {{ font-size: 1.2rem; color: #aaa; margin-bottom: 16px; text-transform: uppercase; letter-spacing: 2px; }}
        .analytics-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 16px; }}
        .card {{ background: #1a1a1a; border: 1px solid #2a2a2a; border-radius: 8px; padding: 16px; }}
        .card span {{ display: block; font-size: 0.75rem; color: #888; margin-bottom: 6px; text-transform: uppercase; letter-spacing: 1px; }}
        .card strong {{ font-size: 1.1rem; color: #ffffff; }}
        .table-wrapper {{ overflow-x: auto; }}
        table {{ width: 100%; border-collapse: collapse; font-size: 0.9rem; }}
        th {{ background: #1a1a1a; color: #888; text-transform: uppercase; letter-spacing: 1px; font-size: 0.75rem; padding: 12px 16px; text-align: left; border-bottom: 1px solid #2a2a2a; }}
        td {{ padding: 12px 16px; border-bottom: 1px solid #1e1e1e; color: #ccc; }}
        tr:hover td {{ background: #1a1a1a; color: #fff; }}
    </style>
</head>
<body>
    <h1>Audio Asset Catalog</h1>
    <p class="subtitle">Generated by Audio Asset Metadata Manager</p>
    {analytics_html}
    <div class="table-wrapper">
        <table>
            <thead><tr>{headers_html}</tr></thead>
            <tbody>{rows_html}</tbody>
        </table>
    </div>
</body>
</html>"""

        with open(output_file, "w", encoding="utf-8") as file:
            file.write(html)

        print(f"\nCatalog exported: {output_file}")